# Default kitty color scheme

foreground            #dddddd
background            #251B15
selection_foreground  #000000
selection_background  #fffacd

cursor                #cccccc
cursor_text_color     #111111

url_color             #0087bd

# black
color0   #000000
color8   #767676

# red
color1   #cc0403
color9   #f2201f

# green — set to blue so your prompt shows blue
color2   #0d73cc
color10  #1a8fff

# yellow
color3   #cecb00
color11  #fffd00

# blue
color4   #19cb00
color12  #23fd00

# magenta
color5   #cb1ed1
color13  #fd28ff

# cyan
color6   #0dcdcd
color14  #14ffff

# white
color7   #dddddd
color15  #ffffff