font_family Jetbrains Mono
font_size 7

background_opacity 0.85
window_padding_width 15 20

allow_remote_control yes

hide_window_decorations no

scrollback_pager_history_size 0
include current-theme.conf