decoration {
    rounding = 3

    blur {
         enabled = true
        size = 5
        passes = 4

        new_optimizations = true
        xray = false
    }

    active_opacity = 1.0
    inactive_opacity = 1.0
}

general {
    border_size = 2
    col.active_border = rgb(C3A5E6)
    col.inactive_border = rgb(3F3F42)
}
