# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(216, 222, 233, 0.80)
    font_size = 60
    font_family = SF Pro Display Bold
    position = 0, 130
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, .80)
    font_size = 19
    font_family = SF Pro Display Bold
    position = 0, 60
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgba(255, 255, 255, 0.1)
    rounding = -1
    border_size = 0
    border_color = rgba(255, 255, 255, 1)
    rotate = 0
    xray = false

    position = 0, -40
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = rgba(216, 222, 233, 0.80)
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    font_size = 16
    font_family = SF Pro Display Bold
    position = 0, -40
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99"> - </span></i>
    hide_input = false
    position = 0, -118
    halign = center
    valign = center
}